[package]
edition = "2021"
name = "addon"
version = "0.0.1"
authors = ["fanchenio <fanchenio@163.com>", "DarkSky <darksky2048@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24.8"
base64 = "0.21.7"
clipboard-win = "5.1.0"
rusqlite = { version = "0.30.0", features = ["bundled"] }

[dependencies.windows]
version = "0.52.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Storage_FileSystem",
    "Win32_System_SystemInformation",
    "Win32_System_Environment",
    "Win32_UI_Input_Ime",
    "Win32_Globalization",
    "Win32_Graphics_Dwm",
    "Management_Deployment",
    "ApplicationModel",
    "Foundation_Collections",
    "ApplicationModel_Core",
]

[build-dependencies]
napi-build = "2"
static_vcruntime = "2.0"
