import * as Addon from './addon.node'

const {
	ItemLayout,
	ItemSort,
	ItemShowOnly,
	ClassificationData,
	Classification,
	DataSource,
	getFileIcon,
	searchPath,
	getShortcutFileInfo,
	shellExecute,
	systemItemExecute,
	openFileLocation,
	explorerContextMenu,
	getEnvByName,
	isFullscreen,
	switchEnglish,
	createMouseHook,
	enableMouseHook,
	disableMouseHook,
	getCursorPosWindowClassName,
	getClipboardFileList,
	clipboardHasBitmap,
	getClipboardBitmapBase64,
	emptyRecycleBin,
	removeWindowAnimation,
	getAppxList,
} = Addon

export default Addon

export {
	ItemLayout,
	ItemSort,
	ItemShowOnly,
	ClassificationData,
	Classification,
	DataSource,
	getFileIcon,
	searchPath,
	getShortcutFileInfo,
	shellExecute,
	systemItemExecute,
	openFileLocation,
	explorerContextMenu,
	getEnvByName,
	isFullscreen,
	switchEnglish,
	createMouseHook,
	enableMouseHook,
	disableMouseHook,
	getCursorPosWindowClassName,
	getClipboardFileList,
	clipboardHasBitmap,
	getClipboardBitmapBase64,
	emptyRecycleBin,
	removeWindowAnimation,
	getAppxList,
}
